### ISSUE TITLE
Fail to build an archive with a path in include_erts

### ISSUE THREAD

**Issue by michalmuskala** [bitwalker/distillery#11]
When building with a config of:

```elixir
environment :ci do
  set include_erts: "erts/ci"
  set include_src: true
end
```

According to the docs this should be supported, unfortunately it crashes when trying to build the tarball: 
```
** (CaseClauseError) no case clause matching: "erts/ci"
    lib/mix/lib/releases/archiver.ex:80: Mix.Releases.Archiver.update_tar/1
    lib/mix/lib/releases/archiver.ex:19: Mix.Releases.Archiver.archive/1
    lib/distillery/tasks/release.ex:108: Mix.Tasks.Release.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

**Comment by bitwalker** [comment]
Fixed with your PR. Thanks again!
