### ISSUE TITLE
Improve overlay docs

### ISSUE THREAD

**Issue by liketemple** [bitwalker/distillery#222]
rel config.ex:
```
environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :"%iu(,;RB@AF47R,s8<mOg5t*?uFuT9l<GEQ&ai9<R./sRx<X:cvyk|Rn9DDmq^nc"
  set overlays: [
    mkdir: "test"
  ]
end
```
it works fine and make a directory: _build/dev/rel/App/test.
But, when I add a copy option,
```
  set overlays: [
    mkdir: "test",
    copy: {"patha/file","pathb/file"}
  ]
```
I got a message like: 
```
** (Mix.Releases.Config.LoadError) could not load release config rel/config.exs
    ** (ArgumentError) expected overlay to be an overlay type and options, but got: {:copy, {"patha/file", "pathb/file"}}
    (distillery) lib/mix/lib/releases/config/config.ex:330: anonymous fn/2 in Mix.Releases.Config.validate!/1
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (distillery) lib/mix/lib/releases/config/config.ex:323: anonymous fn/3 in Mix.Releases.Config.validate!/1
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (distillery) lib/mix/lib/releases/config/config.ex:313: Mix.Releases.Config.validate!/1
    (distillery) lib/mix/lib/releases/config/config.ex:285: Mix.Releases.Config.read_string!/1
    (distillery) lib/mix/lib/releases/config/config.ex:298: Mix.Releases.Config.read!/1
    (distillery) lib/mix/lib/releases/config/config.ex:54: Mix.Releases.Config.get/1
```

Any Info would be a great help, thanks!

**Comment by bitwalker** [comment]
It needs to be `{:copy, "patha/file", "pathb/file"}`. I'll make sure the docs are improved here!

**Comment by liketemple** [comment]
Thanks a lot. Since I found the docs show this:
```
- overlays (special keyword list);
    A list of overlay operations to perform against the release, prior to archival,
    such as copying files, symlinking files, etc.
  - copy: {from_path, to_path} (copy a file)
  - link: {from_path, to_path} (symlink a file)
  - mkdir: path (ensure a path exists)
  - template: {template_path, output_path} (generate a file from a template)
```
I wrote the copy option that that way. Thx again.
