### ISSUE TITLE
Connection refused/port not open in release

### ISSUE THREAD

**Issue by skosch** [bitwalker/distillery#37]
Thanks for a wonderful tool! :)

This may or may not be related to distillery, but I'm not sure where else to ask: when I run `MIX_ENV=prod mix phoenix.server` everything runs fine; but when I run `MIX_ENV=prod mix release` it just refuses to open my (hardcoded) port 3000:
```
$> rel/app/bin/app start
$> rel/app/bin/app ping
pong

$> rel/app/bin/app remote_console
Interactive Elixir (1.3.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(remsh2779c646-app@127.0.0.1)1> :inet.i
Port  Module   Recv Sent Owner    Local Address   Foreign Address State     Type   
16576 inet_tcp 0    0    <0.47.0> *:36943         *:*             ACCEPTING STREAM 
16784 inet_tcp 4    32   <0.45.0> localhost:48472 localhost:epmd  ????      STREAM 
:ok
iex(remsh2779c646-app@127.0.0.1)2> 
^C

$> curl localhost:3000
curl: (7) Failed to connect to localhost port 3000: Connection refused

$> lsof -Pan -p `rel/app/bin/app pid` -i
COMMAND   PID      USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
beam    32053 sebastian    7u  IPv4 334710      0t0  TCP *:39078 (LISTEN)
beam    32053 sebastian    8u  IPv4 334712      0t0  TCP 127.0.0.1:59504->127.0.0.1:4369 (ESTABLISHED)
beam    32053 sebastian   10u  IPv4 334721      0t0  TCP 127.0.0.1:38123->127.0.0.1:5432 (ESTABLISHED)
beam    32053 sebastian   11u  IPv4 334725      0t0  TCP 127.0.0.1:50733->127.0.0.1:5432 (ESTABLISHED)
beam    32053 sebastian   13u  IPv4 334729      0t0  TCP 127.0.0.1:45947->127.0.0.1:5432 (ESTABLISHED)
beam    32053 sebastian   14u  IPv4 334733      0t0  TCP 127.0.0.1:47103->127.0.0.1:5432 (ESTABLISHED)
beam    32053 sebastian   15u  IPv4 334737      0t0  TCP 127.0.0.1:35645->127.0.0.1:5432 (ESTABLISHED)
beam    32053 sebastian   16u  IPv4 334741      0t0  TCP 127.0.0.1:49622->127.0.0.1:5432 (ESTABLISHED)
beam    32053 sebastian   17u  IPv4 334749      0t0  TCP 127.0.0.1:54624->127.0.0.1:5432 (ESTABLISHED)
beam    32053 sebastian   18u  IPv4 334755      0t0  TCP 127.0.0.1:49296->127.0.0.1:5432 (ESTABLISHED)
beam    32053 sebastian   19u  IPv4 334759      0t0  TCP 127.0.0.1:50739->127.0.0.1:5432 (ESTABLISHED)
beam    32053 sebastian   20u  IPv4 334764      0t0  TCP 127.0.0.1:37403->127.0.0.1:5432 (ESTABLISHED)

$> curl localhost:39078
curl: (52) Empty reply from server

$> less rel/app/log/erlang.log.1 
=====
===== LOGGING STARTED Fri Aug 12 00:04:15 EDT 2016
=====
Exec: /opt/rcra/erts-8.0/bin/erlexec -boot /opt/rcra/releases/0.0.1/app -boot_var ER
TS_LIB_DIR /opt/rcra/erts-8.0/../lib -env ERL_LIBS /opt/rcra/lib -pa /opt/rcra/lib/a
pp-0.0.1/consolidated -args_file /opt/rcra/releases/0.0.1/vm.args -config /opt/rcra/
releases/0.0.1/sys.config -mode embedded -user Elixir.IEx.CLI -extra --no-halt +iex 
-- console --
Root: /opt/rcra
/opt/rcra
Eshell V8.0  (abort with ^G)
Interactive Elixir (1.3.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(app@127.0.0.1)1> 

$> less rel/app/log/run_erl.log  
run_erl [32675] Fri Aug 12 00:04:15 2016
Args before exec of shell:
run_erl [32675] Fri Aug 12 00:04:15 2016
argv[0] = sh
run_erl [32675] Fri Aug 12 00:04:15 2016
argv[1] = -c
run_erl [32675] Fri Aug 12 00:04:15 2016
argv[2] = exec "/opt/rcra/bin/app" "console" -- 

```
Here is how I hardcode my port:
```
config :app, App.Endpoint,
  http: [port: 3000],
  url: [host: "xxxxxxxxxxx.ca", port: 80],
  cache_static_manifest: "priv/static/manifest.json"
```
Is there something wrong with my configuration? Could this be due to distillery? If yes, could error messaging be improved? I'm at a complete loss where to even start diagnosing this. Thanks a ton in advance for any ideas!

**Comment by bitwalker** [comment]
Could you dump the result of `Application.get_env(:app, App.Endpoint)`? It doesn't look like your application is actually listening on port 3000, but it's not trying and failing, as it would cause the release to crash for sure, which indicates that it's either binding to a random ephemeral port, or your endpoint is not starting at all. Seeing what's in the config should help.

It might also be worth running `bin/app foreground` and see if you get any error logging output that isn't showing up in the `run_erl` logs.

**Comment by skosch** [comment]
Thank you!

```
$> bin/app console
iex(app@127.0.0.1)1> Application.get_env(:app, App.Endpoint)
[root: "/home/sebastian/projects/cra", 
 render_errors: [accepts: ["html", "json"]],
 pubsub: [name: App.PubSub, adapter: Phoenix.PubSub.PG2], http: [port: 3000],
 url: [host: "[corporate_intranet_site].ca", port: 80],
 cache_static_manifest: "priv/static/manifest.json",
 secret_key_base: "[removed]"]

$> bin/app foreground
Exec: /opt/rcra/erts-8.0/bin/erlexec -noshell -noinput +Bd -boot /opt/rcra/releases/0.0.1/app -mode embedded -config /opt/rcra/releases/0.0.1/sys.config -boot_var ERTS_LIB_DIR /opt/rcra/erts-8.0/../lib -args_file /opt/rcra/releases/0.0.1/vm.args -env ERL_LIBS /opt/rcra/lib -pa /opt/rcra/lib/app-0.0.1/consolidated -extra -- foreground
Root: /opt/rcra
```
So, nothing. But *then* I tried something else on a whim and found
```
iex(remshd9ef01e0-app@127.0.0.1)6> Application.ensure_all_started(:app)

23:46:32.534 [info]  Application app exited: App.start(:normal, []) returned an error: shutdown: failed to start child: App.Repo
    ** (EXIT) an exception was raised:
        ** (ArgumentError) configuration for App.Repo not specified in :app environment
            (ecto) lib/ecto/repo/supervisor.ex:23: Ecto.Repo.Supervisor.config/3
            (ecto) lib/ecto/repo/supervisor.ex:9: Ecto.Repo.Supervisor.start_link/4
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:348: :supervisor.start_children/3
            (stdlib) supervisor.erl:314: :supervisor.init_children/2
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

  [etc. – everything else stopped as a result, too]
```
... which is strange because I do have in my prod.secret.exs:
```
# Configure your database
config :app, App.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "[removed]",
  database: "cra_prod",
  hostname: "localhost",
  pool_size: 10
```
and I know that it reads this, too, because I originally had both the database name and the password wrong and it complained loud and clear. Is that a red herring? Any further ideas?

**Comment by skosch** [comment]
Never mind what I just wrote: the error described above (Repo configs going missing) only shows on the remote machine (which doesn't have Erlang installed) and *only* when using `remote_console`. When running locally on my laptop, both `get_env` and `ensure_all_started` return the expected results inside `console`, `attach` and `remote_console`. But when running remotely, only `console`/`attach` let me run those commands successfuly, while using `remote_console` doesn't (it also doesn't display the line `Erlang/OTP 19 [erts-8.0] [source-6dc93c1] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]`).

This does **not** mean that when I run locally, port 3000 is open – it's not. This is just to add another mystery to the list.

At any rate, the configuration is there, and it says `port: 3000`, and everything seems fine except the port isn't open. Really scratching my head now.

**Comment by bitwalker** [comment]
What's in the list when you run `Application.started_applications()`? I can't shake the feeling that something isn't being started. Could I see your `mix.exs` too? You can strip out anything sensitive, just need the project/application definition primarily.

**Comment by skosch** [comment]
Sure:
```
iex(app@127.0.0.1)2> Application.started_applications()
[{:app, 'app', '0.0.1'}, {:timex_ecto, 'timex_ecto', '3.0.3'},
 {:timex,
  'Timex is a rich, comprehensive Date/Time library for Elixir projects, with full timezone support via the :tzdata package.\nIf you need to manipulate dates, times, datetimes, timestamps, etc., then Timex is for you!\n',
  '3.0.5'},
 {:combine, 'A parser combinator library for Elixir projects.', '0.9.1'},
 {:tzdata, 'Tzdata is a parser and library for the tz database.\n', '0.5.8'},
 {:hackney, 'simple HTTP client', '1.6.1'},
 {:metrics, 'A generic interface to different metrics systems in Erlang.',
  '1.0.1'}, {:ssl_verify_fun, [], '1.1.0'},
 {:certifi, 'An OTP library', '0.4.0'}, {:mimerl, 'An OTP library', '1.0.2'},
 {:idna, 'A pure Erlang IDNA implementation', '1.2.0'},
 {:secure_random, 'A convienance library based on Ruby\'s SecureRandom',
  '0.5.0'},
 {:mailman, 'Library providing a clean way of defining mailers in Elixir apps',
  '0.2.2'},
 {:gen_smtp, 'A generic Erlang SMTP server/client framework', '0.11.0'},
 {:eiconv, 'iconv nif interface', '1.1'},
 {:ssl, 'Erlang/OTP SSL application', '8.0'},
 {:public_key, 'Public key infrastructure', '1.2'},
 {:asn1, 'The Erlang ASN1 compiler version 4.0.3', '4.0.3'},
 {:absinthe_relay, 'absinthe_relay', '0.9.4'},
 {:absinthe_plug, 'absinthe_plug', '1.1.3'}, {:absinthe, 'absinthe', '1.1.8'},
 {:postgrex, 'PostgreSQL driver for Elixir.', '0.11.2'},
 {:db_connection,
  'Database connection behaviour for database transactions and connection pooling\n',
  '1.0.0-rc.4'},
 {:connection, 'Connection behaviour for connection processes\n', '1.0.4'},
 {:phoenix_pubsub, 'Distributed PubSub and Presence platform\n', '1.0.0'},
 {:phoenix_ecto, 'Integration between Phoenix & Ecto', '3.0.1'},
 {:ecto, 'A database wrapper and language integrated query for Elixir.\n',
  '2.0.4'}, {:poolboy, 'A hunky Erlang worker pool factory', '1.5.1'},
 {:decimal, 'Arbitrary precision decimal arithmetic for Elixir.\n', '1.1.2'},
 {:gettext, 'Internationalization and localization through gettext', '0.11.0'},
 {:cowboy, 'Small, fast, modular HTTP server.', '1.0.4'},
 {:cowlib, 'Support library for manipulating Web protocols.', '1.0.2'},
 {:ranch, 'Socket acceptor pool for TCP protocols.', '1.2.1'},
 {:phoenix_html,
  'Phoenix.HTML functions for working with HTML strings and templates',
  '2.6.2'},
 {:phoenix,
  'Productive. Reliable. Fast. A productive web framework that\ndoes not compromise speed and maintainability.\n',
  '1.2.0'}, {:eex, 'eex', '1.3.1'},
 {:poison, 'The fastest JSON library for Elixir', '1.5.2'},
 {:plug,
  'A specification and conveniences for composable modules between web applications',
  '1.2.0'}, {:mime, 'A MIME type module for Elixir', '1.0.1'},
 {:logger, 'logger', '1.3.1'}, {:crypto, 'CRYPTO', '3.7'},
 {:iex, 'iex', '1.3.1'}, {:elixir, 'elixir', '1.3.1'},
 {:compiler, 'ERTS  CXC 138 10', '7.0'}, {:sasl, 'SASL  CXC 138 11', '3.0'},
 {:stdlib, 'ERTS  CXC 138 10', '3.0'}, {:kernel, 'ERTS  CXC 138 10', '5.0'}]
```
And the mix file:
```
defmodule App.Mixfile do
  use Mix.Project

  def project do
    [app: :app,
     version: "0.0.1",
     elixir: "~> 1.3.1",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix, :gettext] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     aliases: aliases,
     deps: deps,
     dialyzer: [plt_apps: [:erts, :kernel, :stdlib, :ecto, :phoenix_ecto, :absinthe, :absinthe_relay, :absinthe_plug]],
   ]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [mod: {App, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :phoenix_pubsub, :postgrex, :ecto,
                    :absinthe, :absinthe_plug, :absinthe_relay,
                    :mailman, :eiconv,
                    :secure_random, :timex, :timex_ecto]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [{:phoenix, "~> 1.2.0"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, "~> 0.11.2"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0.5", only: :dev},
     {:gettext, "~> 0.9"},
     {:cowboy, "~> 1.0"},
     {:oauth2, "~> 0.5"},
     {:ecto, "~> 2.0.2"},
     {:absinthe, "~> 1.1.7"},
     {:absinthe_plug, "~> 1.1.3"},
     {:absinthe_relay, "~> 0.9.4"},
     {:poison, "~> 1.5.0"},
     {:mailman, "~> 0.2.2"},
     {:eiconv, github: "zotonic/eiconv"},
     {:secure_random, "~> 0.2"},
     {:dialyxir, "~> 0.3", only: [:dev]},
     {:credo, "~> 0.4.5", only: [:dev, :test]},
     {:timex, "~> 3.0.1"},
     {:timex_ecto, "~> 3.0.0"},
     {:distillery, "~> 0.9"},
   ]
  end

  # Aliases are shortcut or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
     "ecto.reset": ["ecto.drop", "ecto.setup"]]
  end
end
```

**Comment by bitwalker** [comment]
Are you able to reproduce with an app you can share with me? Might be as simple as just creating a new app with all the same deps. I'm out of ideas as to what's causing the problem here, but having a repro case will help figure it out. Also, what OS are you building/running the release on?

**Comment by skosch** [comment]
Both on Ubuntu, 64bit – let me see what I can come up with to share with you. Thanks :)

**Comment by bitwalker** [comment]
Oh! I forgot one important thing, do you have `server: true` in your endpoint config? Like so:

```elixir
config :myapp, MyApp.Endpoint,
  server: true
```

That has to be there when running via a release.

**Comment by skosch** [comment]
Oh. That was it. 

Just did some googling and found that this info is buried in http://www.phoenixframework.org/v0.13.1/docs/advanced-deployment – though it's not part of what `mix phoenix.new` puts into the prod config files, for some reason.

Maybe you should highlight this parameter on your "Runtime Configuration" page too, or just set this to true by default when a distillery release is started?

Anyways, thanks a million. I would have never figured this out!

**Comment by bitwalker** [comment]
Yeah I'll find a good place in the docs to reference that guide, and call out that setting in particular. It's been awhile since it came up last, or I would've been faster on the draw connecting the dots. Glad we got it sorted!

**Comment by shribe** [comment]
FYI, that bit me this morning... Really wondering if it and/or brief comment shouldn't be generated into prod.exs?

**Comment by aphillipo** [comment]
Maybe someone should create a phoenix pull request for this...

**Comment by michalmuskala** [comment]
The phoenix generator already does this since 2 years https://github.com/phoenixframework/phoenix/blob/master/installer/templates/new/config/prod.exs#L47-L58

**Comment by d-led** [comment]
just had a similar issue when running in WSL (Windows Subsystem for Linux), which didn't allow IPv6 connections. Removed the `:inet6` option from all configs, and it worked. Noticed this, as the dev config didn't have the option, and it worked
