### ISSUE TITLE
Permissions error with strip_debug_info set to true

### ISSUE THREAD

**Issue by fazibear** [bitwalker/distillery#429]
### Steps to reproduce

When I'm trying to create the release with `strip_debug_info` option I got an error. Without it, it works.

### Verbose Logs

```
env MIX_ENV=prod mix release --verbose
==> Loading configuration..
==> Assembling release..
==> Building release rzjb:0.1.0 using environment prod
==> Discovered applications:
...
==> Generated overlay vars:
    release_name=:rzjb
    release_version="0.1.0"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts=true
    include_src=false
    include_system_libs=true
    erl_opts=""
    run_erl_env=""
    erts_vsn="10.0.1"
    output_dir="_build/prod/rel/rzjb"
==> Copying applications to _build/prod/rel/rzjb
==> Generating nodetool
==> Generating start_erl.data
==> Generating vm.args
==> Generating sys.config from config/config.exs
==> Including ERTS 10.0.1 from /usr/local/Cellar/erlang/21.0.1/lib/erlang/erts-10.0.1
==> Generating boot script
==> Generating RELEASES
==> Generating start_clean.boot
==> Generating no_dot_erlang.boot
==> Applying overlays
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_configure.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/post_configure.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_start.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/post_start.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_stop.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/post_stop.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/post_upgrade.d
==> Applying copy overlay
    src: _build/prod/lib/distillery/priv/libexec
    dst: releases/0.1.0/libexec
==> Applying mkdir overlay
    dst: releases/0.1.0/commands
==> Packaging release..
==> Archiving rzjb-0.1.0
==> Writing tarball to _build/prod/rel/rzjb/releases/0.1.0/rzjb.tar.gz
==> Updating tarball
==> You have strip_debug_info set to true.
    Please be aware that if you plan on performing hot upgrades later,
    this setting will prevent you from doing so without a rolling restart.
    You may ignore this warning if you have no plans to use hot upgrades.
==> Stripping release (/tmp/.tmp_dir197466788)
==> Erlang error: {:archiver, :beam_lib, {:file_error, '/tmp/.tmp_dir197466788/lib/asn1-5.0.6/ebin/asn1rt_nif.beam', :eacces}}:
    (stdlib) beam_lib.erl:907: :beam_lib.error/1
    (stdlib) beam_lib.erl:410: :beam_lib."-strip_fils/1-lc$^0/1-0-"/1
    (stdlib) beam_lib.erl:410: :beam_lib."-strip_fils/1-lc$^0/1-0-"/1
    (stdlib) beam_lib.erl:410: :beam_lib.strip_fils/1
    (stdlib) beam_lib.erl:210: :beam_lib.strip_release/1
    (distillery) lib/mix/lib/releases/archiver.ex:178: Mix.Releases.Archiver.strip_release/2
    (distillery) lib/mix/lib/releases/archiver.ex:86: Mix.Releases.Archiver.update_tar/1
    (distillery) lib/mix/lib/releases/archiver.ex:18: Mix.Releases.Archiver.archive/1
```

### Description of issue

- Should create stripped release
- OSX, Erlang 20.0.1, Elixir 1.6.6

**Comment by bitwalker** [comment]
The error is saying that `:beam_lib` (which is invoked by Distillery) doesn't have permission to modify that file for some reason - can you check what permissions are applied to that file and confirm whether or not the user running `mix release` has permissions to modify that path?

**Comment by fazibear** [comment]
It's not the permission problem, I've cleared out `/tmp` before tired to make a release with the same result.

**Comment by fazibear** [comment]
```
-r--r--r--  1 fazibear  wheel  3852 Jul  1 15:22 /tmp/.tmp_dir905786731/lib/asn1-5.0.6/ebin/asn1rt_nif.beam
```

**Comment by bitwalker** [comment]
The permissions are copied directly from the source file IIRC. Can you check whether the same permissions are set on your Erlang installation, or at least on the `asn1` application BEAMs? That would certainly explain why stripping them fails though. We may be able to add a check for this to Distillery, but it depends on whether we can just check the root Erlang installation directory, or if we need to check every file - the former is doable, the latter is far too expensive.

**Comment by bitwalker** [comment]
You could use a plugin, and do the permissions check/modification in `after_assembly` or `before_package`, since stripping the BEAM files happens during the packaging/archival phase.

**Comment by gallexme** [comment]
@fazibear  any updates on this?
