### ISSUE TITLE
invalid ERTS path, cannot determine version

### ISSUE THREAD

**Issue by omin** [bitwalker/distillery#43]
### Steps to reproduce

add `include_erts: "/usr/local/Cellar/erlang/19.0.2/lib/erlang/lib"` to `rel/config.exs`
`$MIX_ENV=prod mix release --env=prod`

### Verbose Logs
~~~
$ MIX_ENV=prod mix release --env=prod --verbose
==> Loading configuration..
==> Assembling release..
==> Building release omin:0.0.1 using environment prod
==> Discovered applications:
  sasl-3.0
    from: /usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/sasl-3.0
    applications:
      kernel
      stdlib
    includes: none

  iex-1.3.2
    from: /usr/local/Cellar/elixir/1.3.2/bin/../lib/iex
    applications:
      kernel
      stdlib
      elixir
    includes: none

  omin-0.0.1
    from: _build/prod/lib/omin
    applications:
      kernel
      stdlib
      elixir
      phoenix
      phoenix_pubsub
      phoenix_html
      cowboy
      logger
      gettext
      phoenix_ecto
      postgrex
    includes: none

  kernel-5.0
    from: /usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/kernel-5.0
    applications: none
    includes: none

  stdlib-3.0.1
    from: /usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/stdlib-3.0.1
    applications:
      kernel
    includes: none

  elixir-1.3.2
    from: /usr/local/Cellar/elixir/1.3.2/bin/../lib/elixir
    applications:
      kernel
      stdlib
      compiler
    includes: none

  compiler-7.0.1
    from: /usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/compiler-7.0.1
    applications:
      kernel
      stdlib
    includes: none

  phoenix-1.2.1
    from: _build/prod/lib/phoenix
    applications:
      kernel
      stdlib
      elixir
      plug
      poison
      logger
      eex
    includes: none

  plug-1.2.0
    from: _build/prod/lib/plug
    applications:
      kernel
      stdlib
      elixir
      crypto
      logger
      mime
    includes: none

  crypto-3.7
    from: /usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/crypto-3.7
    applications:
      kernel
      stdlib
    includes: none

  logger-1.3.2
    from: /usr/local/Cellar/elixir/1.3.2/bin/../lib/logger
    applications:
      kernel
      stdlib
      elixir
    includes: none

  mime-1.0.1
    from: _build/prod/lib/mime
    applications:
      kernel
      stdlib
      elixir
    includes: none

  poison-2.2.0
    from: _build/prod/lib/poison
    applications:
      kernel
      stdlib
      elixir
    includes: none

  eex-1.3.2
    from: /usr/local/Cellar/elixir/1.3.2/bin/../lib/eex
    applications:
      kernel
      stdlib
      elixir
    includes: none

  phoenix_pubsub-1.0.0
    from: _build/prod/lib/phoenix_pubsub
    applications:
      kernel
      stdlib
      elixir
      logger
      crypto
    includes: none

  phoenix_html-2.6.2
    from: _build/prod/lib/phoenix_html
    applications:
      kernel
      stdlib
      elixir
      logger
      plug
    includes: none

  cowboy-1.0.4
    from: _build/prod/lib/cowboy
    applications:
      kernel
      stdlib
      ranch
      cowlib
      crypto
    includes: none

  ranch-1.2.1
    from: _build/prod/lib/ranch
    applications:
      kernel
      stdlib
    includes: none

  cowlib-1.0.2
    from: _build/prod/lib/cowlib
    applications:
      kernel
      stdlib
      crypto
    includes: none

  gettext-0.11.0
    from: _build/prod/lib/gettext
    applications:
      kernel
      stdlib
      elixir
      logger
    includes: none

  phoenix_ecto-3.0.1
    from: _build/prod/lib/phoenix_ecto
    applications:
      kernel
      stdlib
      elixir
      logger
      ecto
      plug
    includes: none

  ecto-2.0.4
    from: _build/prod/lib/ecto
    applications:
      kernel
      stdlib
      elixir
      logger
      decimal
      poolboy
    includes: none

  decimal-1.1.2
    from: _build/prod/lib/decimal
    applications:
      kernel
      stdlib
      elixir
    includes: none

  poolboy-1.5.1
    from: _build/prod/lib/poolboy
    applications:
      kernel
      stdlib
    includes: none

  postgrex-0.11.2
    from: _build/prod/lib/postgrex
    applications:
      kernel
      stdlib
      elixir
      logger
      db_connection
      decimal
    includes: none

  db_connection-1.0.0-rc.4
    from: _build/prod/lib/db_connection
    applications:
      kernel
      stdlib
      elixir
      logger
      connection
    includes: none

  connection-1.0.4
    from: _build/prod/lib/connection
    applications:
      kernel
      stdlib
      elixir
    includes: none

==> Generated overlay vars:
    release_name=:omin
    release_version="0.0.1"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts="/usr/local/Cellar/erlang/19.0.2/lib/"
    include_src=false
    include_system_libs=true
    erl_opts=""
    erts_vsn={:error, "invalid ERTS path, cannot determine version"}
    output_dir="rel/omin"
==> Copying applications to rel/omin
==> Generating nodetool
==> Failed to build release:
    protocol String.Chars not implemented for {:error, "invalid ERTS path, cannot determine version"}
~~~

### Description of issue
I expected it to successfully build a release.
I'm using OS X 10.11.6, erts-8.0.2, Elixir 1.3.2.
My `rel/config.exs` file is the default generated by `$mix release.init` except `include_erts: "/usr/local/Cellar/erlang/19.0.2/lib/erlang/lib"`.

**Comment by omin** [comment]
Some improvement but still not working.
```
==> Loading configuration..
==> Assembling release..
==> Building release omin:0.0.1 using environment prod
==> Discovered applications:
  sasl-3.0
    from: /usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/sasl-3.0
    applications:
      kernel
      stdlib
    includes: none

  iex-1.3.2
    from: /usr/local/Cellar/elixir/1.3.2/bin/../lib/iex
    applications:
      kernel
      stdlib
      elixir
    includes: none

  omin-0.0.1
    from: _build/prod/lib/omin
    applications:
      kernel
      stdlib
      elixir
      phoenix
      phoenix_pubsub
      phoenix_html
      cowboy
      logger
      gettext
      phoenix_ecto
      postgrex
    includes: none

  kernel-5.0
    from: /usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/kernel-5.0
    applications: none
    includes: none

  stdlib-3.0.1
    from: /usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/stdlib-3.0.1
    applications:
      kernel
    includes: none

  elixir-1.3.2
    from: /usr/local/Cellar/elixir/1.3.2/bin/../lib/elixir
    applications:
      kernel
      stdlib
      compiler
    includes: none

  compiler-7.0.1
    from: /usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/compiler-7.0.1
    applications:
      kernel
      stdlib
    includes: none

  phoenix-1.2.1
    from: _build/prod/lib/phoenix
    applications:
      kernel
      stdlib
      elixir
      plug
      poison
      logger
      eex
    includes: none

  plug-1.2.0
    from: _build/prod/lib/plug
    applications:
      kernel
      stdlib
      elixir
      crypto
      logger
      mime
    includes: none

  crypto-3.7
    from: /usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/crypto-3.7
    applications:
      kernel
      stdlib
    includes: none

  logger-1.3.2
    from: /usr/local/Cellar/elixir/1.3.2/bin/../lib/logger
    applications:
      kernel
      stdlib
      elixir
    includes: none

  mime-1.0.1
    from: _build/prod/lib/mime
    applications:
      kernel
      stdlib
      elixir
    includes: none

  poison-2.2.0
    from: _build/prod/lib/poison
    applications:
      kernel
      stdlib
      elixir
    includes: none

  eex-1.3.2
    from: /usr/local/Cellar/elixir/1.3.2/bin/../lib/eex
    applications:
      kernel
      stdlib
      elixir
    includes: none

  phoenix_pubsub-1.0.0
    from: _build/prod/lib/phoenix_pubsub
    applications:
      kernel
      stdlib
      elixir
      logger
      crypto
    includes: none

  phoenix_html-2.6.2
    from: _build/prod/lib/phoenix_html
    applications:
      kernel
      stdlib
      elixir
      logger
      plug
    includes: none

  cowboy-1.0.4
    from: _build/prod/lib/cowboy
    applications:
      kernel
      stdlib
      ranch
      cowlib
      crypto
    includes: none

  ranch-1.2.1
    from: _build/prod/lib/ranch
    applications:
      kernel
      stdlib
    includes: none

  cowlib-1.0.2
    from: _build/prod/lib/cowlib
    applications:
      kernel
      stdlib
      crypto
    includes: none

  gettext-0.11.0
    from: _build/prod/lib/gettext
    applications:
      kernel
      stdlib
      elixir
      logger
    includes: none

  phoenix_ecto-3.0.1
    from: _build/prod/lib/phoenix_ecto
    applications:
      kernel
      stdlib
      elixir
      logger
      ecto
      plug
    includes: none

  ecto-2.0.4
    from: _build/prod/lib/ecto
    applications:
      kernel
      stdlib
      elixir
      logger
      decimal
      poolboy
    includes: none

  decimal-1.1.2
    from: _build/prod/lib/decimal
    applications:
      kernel
      stdlib
      elixir
    includes: none

  poolboy-1.5.1
    from: _build/prod/lib/poolboy
    applications:
      kernel
      stdlib
    includes: none

  postgrex-0.11.2
    from: _build/prod/lib/postgrex
    applications:
      kernel
      stdlib
      elixir
      logger
      db_connection
      decimal
    includes: none

  db_connection-1.0.0-rc.4
    from: _build/prod/lib/db_connection
    applications:
      kernel
      stdlib
      elixir
      logger
      connection
    includes: none

  connection-1.0.4
    from: _build/prod/lib/connection
    applications:
      kernel
      stdlib
      elixir
    includes: none

==> Generated overlay vars:
    release_name=:omin
    release_version="0.0.1"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts="/usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/"
    include_src=false
    include_system_libs=true
    erl_opts=""
    erts_vsn="8.0.2"
    output_dir="rel/omin"
==> Copying applications to rel/omin
==> Generating nodetool
==> Generating start_erl.data
==> Generating vm.args
==> Generating sys.config from config/config.exs
==> Including ERTS 8.0.2 from /usr/local/Cellar/erlang/19.0.2/lib/erlang/lib/erts-8.0.2
==> Failed to build release:
    Failed during include_erts: :enoent
```

Also is it recommended to install erlang on the production server or use virtual machine to match the OS? If so, which of the two do you recommend? I actually also had trouble getting this to work on exrm and I ended up installing erlang on the server in the past.

**Comment by bitwalker** [comment]
I'll address this today, as I was working on some stuff related to this the past few days. What you do is really down to what's the most convenient. In general, my approach is to build releases in Docker, including ERTS, then deploy to the prod host - these days though we are running containers in production, so it's a non-issue. Installing Erlang on the host is probably the easiest, but more risky if you plan to run more than one thing on that host. Building in Docker is probably the easiest approach that keeps applications isolated from each other, and the approach I'd recommend generally when cross-compiling.

However this method of including ERTS from a given directory should not be an issue, so I'm going to make sure it's working and get back to you here.

**Comment by bitwalker** [comment]
Found the issue here, could you give master a try and let me know if things are working for you?

**Comment by omin** [comment]
There was another error on master when I tried yesterday and I'm getting the same thing right now.

```
$ sudo MIX_ENV=prod mix release --env=prod --verbose
==> distillery
Compiling 17 files (.ex)
Generated distillery app
==> omin
Compiling 12 files (.ex)
Generated omin app
==> Loading configuration..
==> Assembling release..
==> Building release omin:0.0.1 using environment prod
** (UndefinedFunctionError) function nil.config/0 is undefined or private
    nil.config()
    Mix.Releases.Assembler.apply_configuration/2
    lib/mix/lib/releases/assembler.ex:27: Mix.Releases.Assembler.assemble/1
    lib/distillery/tasks/release.ex:100: Mix.Tasks.Release.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

**Comment by bitwalker** [comment]
Ok I'll take a look as soon as I can, must be related to recent changes

**Comment by omin** [comment]
No hurry :) I installed Erlang on the host to simplify everything for now.

**Comment by bitwalker** [comment]
@omin Can you give me access to the repo for this, or to a repo which reproduces the `nil.config` error? I can't reproduce it, but the conditions for it occurring must be very unique based on the code, so if it's happening in master it's definitely a bug, or at least a corner case which should be handled somehow.

**Comment by bitwalker** [comment]
Correction, found the issue, master will be updated in a few minutes :)

**Comment by omin** [comment]
Whoa that was quick. I was just creating a new project for ya

**Comment by bitwalker** [comment]
Give master a try now, should be good to go!

**Comment by omin** [comment]
Another error :(

```
$ MIX_ENV=prod mix release --env=prod --verbose
==> distillery
Compiling 17 files (.ex)
Generated distillery app
==> testing_distillery
Compiling 12 files (.ex)
Generated testing_distillery app
==> Loading configuration..
==> Assembling release..
==> Building release testing_distillery:0.0.1 using environment prod
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Mix.Releases.App.get_children/1
    lib/mix/lib/releases/models/app.ex:76: anonymous fn({:phoenix_live_reload, "~> 1.0", [only: :dev]}) in Mix.Releases.App.get_children/1
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/lib/releases/models/app.ex:39: Mix.Releases.App.new/2
    lib/mix/lib/releases/utils.ex:198: Mix.Releases.Utils.get_apps/1
    lib/mix/lib/releases/assembler.ex:78: Mix.Releases.Assembler.apply_configuration/2
    lib/mix/lib/releases/assembler.ex:27: Mix.Releases.Assembler.assemble/1
    lib/distillery/tasks/release.ex:100: Mix.Tasks.Release.run/1
```

**Comment by bitwalker** [comment]
Ok, that was another recent change, missing a case clause for deps with options. I pushed a fix to master, can you try again (sorry)?

**Comment by omin** [comment]
No problem. I wish I could do more to help. This time it worked!

**Comment by bitwalker** [comment]
Awesome! Thanks for helping me work through this! We've had a few changes recently and your use case actually hit all of the updated code paths haha, so I'm glad we got it sorted!
