### ISSUE TITLE
Compilation error on 2.0.0-rc.1

### ISSUE THREAD

**Issue by ishikawa** [bitwalker/distillery#442]
### Steps to reproduce

In my `mix.exs`

```elixir
  defp deps do
    [
...
      {:distillery, "~> 2.0.0-rc.1"},
    ]
  end
```

`mix deps.get` and compile

### Verbose Logs

```
$ mix compile
==> distillery
Compiling 28 files (.ex)

== Compilation error in file lib/mix/lib/releases/appup/transform.ex ==
** (File.Error) could not read file "/proj/deps/distillery/lib/mix/lib/releases/appup/../../../../../test/support/purge_transform.ex": no such file or directory
    (elixir) lib/file.ex:319: File.read!/1
    lib/mix/lib/releases/appup/transform.ex:14: (module)
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
could not compile dependency :distillery, "mix compile" failed. You can recompile this dependency with "mix deps.compile distillery", update it with "mix deps.update distillery" or clean it with "mix deps.clean distillery"
** (exit) 1
    (mix) lib/mix/tasks/cmd.ex:41: Mix.Tasks.Cmd.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/project.ex:348: Mix.Project.in_project/4
    (elixir) lib/file.ex:1443: File.cd!/2
    (mix) lib/mix/task.ex:416: anonymous fn/4 in Mix.Task.recur/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/task.ex:415: Mix.Task.recur/1
    (mix) lib/mix/project_stack.ex:202: Mix.ProjectStack.recur/1
```

### Description of issue

- What are the expected results?
  - No compilation failure
- What OS, Erlang/Elixir versions are you seeing this issue on?
  - Mac OS X 10.12.6
  - Elixir 1.7.1
  - Erlang/OTP 21

**Comment by bitwalker** [comment]
Fixed in 2.0.0-rc.2. Sorry about that!
