### ISSUE TITLE
Release failed: no function clause matching in List.to_string/1

### ISSUE THREAD

**Issue by OleMchls** [bitwalker/distillery#462]
### Steps to reproduce

We have an umbrella app that we just migrated to 1.7, and had to update to dialyzer 2.0 because of #431

```
# mix.lock
  "distillery": {:hex, :distillery, "2.0.0-rc.7", "1fd2933f1d3d39a9fbb62b2adbe5a0d0222348891eabef9cc327b91e80a1cf53", [:mix], [{:artificery, "~> 0.2", [hex: :artificery, repo: "hexpm", optional: false]}], "hexpm"},
```

When running `MIX_ENV=prod mix release --env=prod --executable --verbose` we see the following error:

```
==> Release failed: no function clause matching in List.to_string/1
    (elixir) lib/list.ex:821: List.to_string("_build/prod/rel/dnsrr/releases/0.1.0/dnsrr.tar.gz")
    (distillery) lib/mix/lib/releases/archiver.ex:28: Mix.Releases.Archiver.archive/1
    (distillery) lib/distillery/tasks/release.ex:138: Mix.Tasks.Release.do_release/2
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) src/elixir_compiler.erl:71: :elixir_compiler.dispatch/4
    (elixir) src/elixir_compiler.erl:68: :elixir_compiler.compile/3
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/2
```

### Verbose Logs

Paste the output of the release command you ran with the `--verbose` flag
below in the summary tags (this helps keep the issue easy to navigate):

<summary>
  <details>

```
👌  dnsrr git:(disable-builds-on-travis) ✗ MIX_ENV=prod mix release --env=prod --executable --verbose
warning: found quoted keyword "benchmark" but the quotes are not required. Note that keywords are always atoms, even when quoted, and quotes should only be used to introduce keywords with foreign characters in them
  /Users/ole/projects/dnsrr/deps/eventstore/mix.exs:103

==> artificery
Compiling 10 files (.ex)
Generated artificery app
==> distillery
Compiling 33 files (.ex)
Generated distillery app
==> simple_registrar
Compiling 69 files (.ex)
Generated simple_registrar app
==> simple_registrar_web
Compiling 26 files (.ex)
==> Loading configuration..
==> Assembling release..
==> Building release dnsrr:0.1.0 using environment prod
==> Discovered applications:
  > kernel-6.0
  |
  |  from: /usr/local/Cellar/erlang/21.0.4/lib/erlang/lib/kernel-6.0
  |  applications: none
  |  includes: none
  |_____

  > stdlib-3.5.1
  |
  |  from: /usr/local/Cellar/erlang/21.0.4/lib/erlang/lib/stdlib-3.5.1
  |  applications:
  |      :kernel
  |  includes: none
  |_____

  > compiler-7.2.2
  |
  |  from: /usr/local/Cellar/erlang/21.0.4/lib/erlang/lib/compiler-7.2.2
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > elixir-1.7.1
  |
  |  from: /usr/local/Cellar/elixir/1.7.1/bin/../lib/elixir
  |  applications:
  |      :kernel
  |      :stdlib
  |      :compiler
  |  includes: none
  |_____

  > iex-1.7.1
  |
  |  from: /usr/local/Cellar/elixir/1.7.1/bin/../lib/iex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > mix-1.7.1
  |
  |  from: /usr/local/Cellar/elixir/1.7.1/bin/../lib/mix
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > sasl-3.2
  |
  |  from: /usr/local/Cellar/erlang/21.0.4/lib/erlang/lib/sasl-3.2
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > runtime_tools-1.13
  |
  |  from: /usr/local/Cellar/erlang/21.0.4/lib/erlang/lib/runtime_tools-1.13
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > logger-1.7.1
  |
  |  from: /usr/local/Cellar/elixir/1.7.1/bin/../lib/logger
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > artificery-0.2.6
  |
  |  from: _build/prod/lib/artificery
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > distillery-2.0.0-rc.7
  |
  |  from: _build/prod/lib/distillery
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :runtime_tools
  |      :logger
  |      :artificery
  |  includes: none
  |_____

  > crypto-4.3
  |
  |  from: /usr/local/Cellar/erlang/21.0.4/lib/erlang/lib/crypto-4.3
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > asn1-5.0.6
  |
  |  from: /usr/local/Cellar/erlang/21.0.4/lib/erlang/lib/asn1-5.0.6
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > public_key-1.6.1
  |
  |  from: /usr/local/Cellar/erlang/21.0.4/lib/erlang/lib/public_key-1.6.1
  |  applications:
  |      :asn1
  |      :crypto
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > ssl-9.0
  |
  |  from: /usr/local/Cellar/erlang/21.0.4/lib/erlang/lib/ssl-9.0
  |  applications:
  |      :crypto
  |      :public_key
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > socket-0.3.13
  |
  |  from: _build/prod/lib/socket
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :crypto
  |      :ssl
  |  includes: none
  |_____

  > poolboy-1.5.1
  |
  |  from: _build/prod/lib/poolboy
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > xml_builder-0.0.9
  |
  |  from: _build/prod/lib/xml_builder
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > xmerl-1.3.17
  |
  |  from: /usr/local/Cellar/erlang/21.0.4/lib/erlang/lib/xmerl-1.3.17
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > sweet_xml-0.6.5
  |
  |  from: _build/prod/lib/sweet_xml
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :xmerl
  |  includes: none
  |_____

  > exepp-0.1.0
  |
  |  from: _build/prod/lib/exepp
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :xml_builder
  |      :sweet_xml
  |  includes: none
  |_____

  > uuid-1.1.8
  |
  |  from: _build/prod/lib/uuid
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > exepp_client-0.1.0
  |
  |  from: _build/prod/lib/exepp_client
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :socket
  |      :poolboy
  |      :exepp
  |      :uuid
  |  includes: none
  |_____

  > connection-1.0.4
  |
  |  from: _build/prod/lib/connection
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > db_connection-1.1.3
  |
  |  from: _build/prod/lib/db_connection
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :connection
  |  includes: none
  |_____

  > decimal-1.5.0
  |
  |  from: _build/prod/lib/decimal
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > postgrex-0.13.5
  |
  |  from: _build/prod/lib/postgrex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :db_connection
  |      :decimal
  |      :crypto
  |  includes: none
  |_____

  > ecto-2.2.10
  |
  |  from: _build/prod/lib/ecto
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :decimal
  |      :poolboy
  |      :crypto
  |  includes: none
  |_____

  > gen_stage-0.13.1
  |
  |  from: _build/prod/lib/gen_stage
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > fsm-0.3.0
  |
  |  from: _build/prod/lib/fsm
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > poison-3.1.0
  |
  |  from: _build/prod/lib/poison
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > eventstore-0.14.0
  |
  |  from: _build/prod/lib/eventstore
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :poolboy
  |      :gen_stage
  |      :fsm
  |      :poison
  |      :uuid
  |      :postgrex
  |  includes: none
  |_____

  > ecto_atom-1.0.0
  |
  |  from: _build/prod/lib/ecto_atom
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :ecto
  |  includes: none
  |_____

  > simple_registrar-0.0.1
  |
  |  from: _build/prod/lib/simple_registrar
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :runtime_tools
  |      :exepp_client
  |      :postgrex
  |      :ecto
  |      :eventstore
  |      :ecto_atom
  |  includes: none
  |_____

  > gettext-0.15.0
  |
  |  from: _build/prod/lib/gettext
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > ranch-1.3.2
  |
  |  from: _build/prod/lib/ranch
  |  applications:
  |      :kernel
  |      :stdlib
  |      :ssl
  |  includes: none
  |_____

  > cowlib-1.0.2
  |
  |  from: _build/prod/lib/cowlib
  |  applications:
  |      :kernel
  |      :stdlib
  |      :crypto
  |  includes: none
  |_____

  > cowboy-1.1.2
  |
  |  from: _build/prod/lib/cowboy
  |  applications:
  |      :kernel
  |      :stdlib
  |      :ranch
  |      :cowlib
  |      :crypto
  |  includes: none
  |_____

  > mime-1.2.0
  |
  |  from: _build/prod/lib/mime
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > plug-1.5.0
  |
  |  from: _build/prod/lib/plug
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :crypto
  |      :logger
  |      :mime
  |  includes: none
  |_____

  > eex-1.7.1
  |
  |  from: /usr/local/Cellar/elixir/1.7.1/bin/../lib/eex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > phoenix_pubsub-1.0.2
  |
  |  from: _build/prod/lib/phoenix_pubsub
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :crypto
  |  includes: none
  |_____

  > phoenix-1.3.2
  |
  |  from: _build/prod/lib/phoenix
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :plug
  |      :poison
  |      :logger
  |      :eex
  |      :phoenix_pubsub
  |      :crypto
  |  includes: none
  |_____

  > simple_registrar_web-0.0.1
  |
  |  from: _build/prod/lib/simple_registrar_web
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :runtime_tools
  |      :gettext
  |      :cowboy
  |      :phoenix
  |      :simple_registrar
  |  includes: none
  |_____

==> Running validation checks..
    > Mix.Releases.Checks.Erts * PASS
    > Mix.Releases.Checks.Cookie * PASS
    > Mix.Releases.Checks.MissingApps * PASS
    > Mix.Releases.Checks.LoadedOrphanedApps * PASS
==> Generated overlay vars:
    release_name=:dnsrr
    release_version="0.1.0"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts=true
    include_src=false
    include_system_libs=true
    erl_opts=""
    run_erl_env=""
    erts_vsn="10.0.4"
    output_dir="_build/prod/rel/dnsrr"
==> Copying applications to _build/prod/rel/dnsrr
==> Generating start_erl.data
==> Generating vm.args
==> Generating sys.config from config/config.exs
==> Including ERTS 10.0.4 from /usr/local/Cellar/erlang/21.0.4/lib/erlang/erts-10.0.4
==> Generating boot script
==> Generating RELEASES
==> Generating start_clean.boot
==> Generating no_dot_erlang.boot
==> Applying overlays
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_configure.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/post_configure.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_start.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/post_start.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_stop.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/post_stop.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/post_upgrade.d
==> Applying copy overlay
    src: _build/prod/lib/distillery/priv/libexec
    dst: releases/0.1.0/libexec
==> Applying mkdir overlay
    dst: releases/0.1.0/commands
==> Packaging release..
==> Archiving dnsrr-0.1.0
==> Writing archive to /Users/ole/projects/dnsrr/_build/prod/rel/dnsrr/releases/0.1.0/dnsrr.tar.gz
==> Updating archive..
==> Including system libs from current Erlang installation
==> Saving archive..
==> Archive saved!
==> Generating executable..
==> Release failed: no function clause matching in List.to_string/1
    (elixir) lib/list.ex:821: List.to_string("_build/prod/rel/dnsrr/releases/0.1.0/dnsrr.tar.gz")
    (distillery) lib/mix/lib/releases/archiver.ex:28: Mix.Releases.Archiver.archive/1
    (distillery) lib/distillery/tasks/release.ex:138: Mix.Tasks.Release.do_release/2
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) src/elixir_compiler.erl:71: :elixir_compiler.dispatch/4
    (elixir) src/elixir_compiler.erl:68: :elixir_compiler.compile/3
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/2

```

  </details>
</summary>

### Description of issue

- What are the expected results?
A successfull build
- What version of Distillery?
2.0.0-rc.7
- What OS, Erlang/Elixir versions are you seeing this issue on?
OSX 10.13.6 (17G65)
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.7.1 (compiled with Erlang/OTP 21)
- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)
```
# Import all plugins from `rel/plugins`
# They can then be used by adding `plugin MyPlugin` to
# either an environment, or release definition, where
# `MyPlugin` is the name of the plugin module.
Path.join(["rel", "plugins", "*.exs"])
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    # This sets the default release built by `mix release`
    default_release: :default,
    # This sets the default environment used by `mix release`
    default_environment: Mix.env()

# For a full list of config options for both releases
# and environments, visit https://hexdocs.pm/distillery/configuration.html


# You may define one or more environments in this file,
# an environment's settings will override those of a release
# when building in that environment, this combination of release
# and environment configuration is called a profile

environment :dev do
  # If you are running Phoenix, you should make sure that
  # server: true is set and the code reloader is disabled,
  # even in dev mode.
  # It is recommended that you build with MIX_ENV=prod and pass
  # the --env flag to Distillery explicitly if you want to use
  # dev mode.
  set dev_mode: true
  set include_erts: false
  set cookie: :"nope"
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"nope"
end

# You may define one or more releases in this file.
# If you have not set a default release, or selected one
# when running `mix release`, the first release in the file
# will be used by default

release :dnsrr do
  set version: "0.1.0"
  set applications: [
    :runtime_tools,
    simple_registrar: :permanent,
    simple_registrar_web: :permanent
  ]
end


```
- Is there documentation that says one thing, but Distillery does
  another? If so, please link the doc here so it can be updated if
  it's a documentation issue, or so that the fix can be based around
  what's documented.
- If this is a runtime configuration issue, please also provide your config file 
  (with any sensitive information stripped of course). This is almost
  always necessary to understand why some configuration may not be working.

If you do not provide the above information and I need it to help troubleshoot, it may delay things significantly,
as I will have to ask you for all of these things anyway. Help me help you!

----
Edit: Add answers to debugging questions

**Comment by bitwalker** [comment]
Sorry about that! Fixed in master, and I'll have a new release out today

**Comment by OleMchls** [comment]
Thanks for the swift response @bitwalker
