### ISSUE TITLE
Application with `swarm` fails to start on 2.0-pre

### ISSUE THREAD

**Issue by erikreedstrom** [bitwalker/distillery#476]
Application with `swarm` dependency fails to start with following error on crash:

```
Logger - error: {removed_failing_handler,'Elixir.Logger'}
{"Kernel pid terminated",application_controller,"{application_start_failure,swarm,{{shutdown,{failed_to_start_child,'Elixir.Swarm.Tracker',function_clause}},{'Elixir.Swarm',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,swarm,{{shutdown,{failed_to_start_child,'Elixir.Swarm.Tracker',function_clause}},{'Elixir.Swarm',start,[normal,[]]}}})
```

### Steps to reproduce

1. `MIX_ENV=prod mix release --env=prod`
1. `env $(cat .env.prod | xargs) _build/prod/rel/core_api/bin/core_api foreground`

### Verbose Logs

<summary>
  <details>

```
==> Loading configuration..
==> Assembling release..
==> Building release core_api:0.0.0+version using environment prod
==> Discovered applications:
  > kernel-6.0
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/kernel-6.0
  |  applications: none
  |  includes: none
  |_____

  > stdlib-3.5.1
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/stdlib-3.5.1
  |  applications:
  |      :kernel
  |  includes: none
  |_____

  > compiler-7.2.2
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/compiler-7.2.2
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > elixir-1.7.2
  |
  |  from: /Users/erikreedstrom/.asdf/installs/elixir/1.7.2/bin/../lib/elixir
  |  applications:
  |      :kernel
  |      :stdlib
  |      :compiler
  |  includes: none
  |_____

  > iex-1.7.2
  |
  |  from: /Users/erikreedstrom/.asdf/installs/elixir/1.7.2/bin/../lib/iex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > mix-1.7.2
  |
  |  from: /Users/erikreedstrom/.asdf/installs/elixir/1.7.2/bin/../lib/mix
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > sasl-3.2
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/sasl-3.2
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > runtime_tools-1.13
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/runtime_tools-1.13
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > logger-1.7.2
  |
  |  from: /Users/erikreedstrom/.asdf/installs/elixir/1.7.2/bin/../lib/logger
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > artificery-0.2.6
  |
  |  from: _build/prod/lib/artificery
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > distillery-2.0.0-rc.8
  |
  |  from: _build/prod/lib/distillery
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :runtime_tools
  |      :logger
  |      :artificery
  |  includes: none
  |_____

  > p1_utils-1.0.10
  |
  |  from: _build/prod/lib/p1_utils
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > inets-7.0
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/inets-7.0
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > jason-1.1.1
  |
  |  from: _build/prod/lib/jason
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > crypto-4.3
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/crypto-4.3
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > asn1-5.0.6
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/asn1-5.0.6
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > public_key-1.6.1
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/public_key-1.6.1
  |  applications:
  |      :asn1
  |      :crypto
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > ssl-9.0
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/ssl-9.0
  |  applications:
  |      :crypto
  |      :public_key
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > libcluster-3.0.2
  |
  |  from: _build/prod/lib/libcluster
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :inets
  |      :jason
  |      :crypto
  |      :ssl
  |  includes: none
  |_____

  > gen_state_machine-2.0.2
  |
  |  from: _build/prod/lib/gen_state_machine
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > libring-1.3.1
  |
  |  from: _build/prod/lib/libring
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :crypto
  |  includes: none
  |_____

  > swarm-3.3.1
  |
  |  from: _build/prod/lib/swarm
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :crypto
  |      :gen_state_machine
  |      :libring
  |  includes: none
  |_____

  > elixir_uuid-1.2.0
  |
  |  from: _build/prod/lib/elixir_uuid
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > format-0.1.0
  |
  |  from: _build/prod/lib/format
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > elixlsx-0.4.0
  |
  |  from: _build/prod/lib/elixlsx
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > inflex-1.10.0
  |
  |  from: _build/prod/lib/inflex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > gettext-0.15.0
  |
  |  from: _build/prod/lib/gettext
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > sage-0.4.0
  |
  |  from: _build/prod/lib/sage
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > decimal-1.5.0
  |
  |  from: _build/prod/lib/decimal
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > absinthe-1.4.13
  |
  |  from: _build/prod/lib/absinthe
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > elixir_make-0.4.2
  |
  |  from: _build/prod/lib/elixir_make
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > bcrypt_elixir-1.0.9
  |
  |  from: _build/prod/lib/bcrypt_elixir
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :crypto
  |      :elixir_make
  |  includes: none
  |_____

  > comeonin-4.1.1
  |
  |  from: _build/prod/lib/comeonin
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > gen_stage-0.14.0
  |
  |  from: _build/prod/lib/gen_stage
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > flow-0.14.2
  |
  |  from: _build/prod/lib/flow
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :gen_stage
  |  includes: none
  |_____

  > unicode_util_compat-0.3.1
  |
  |  from: _build/prod/lib/unicode_util_compat
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > idna-5.1.2
  |
  |  from: _build/prod/lib/idna
  |  applications:
  |      :kernel
  |      :stdlib
  |      :unicode_util_compat
  |  includes: none
  |_____

  > mimerl-1.0.2
  |
  |  from: _build/prod/lib/mimerl
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > certifi-2.3.1
  |
  |  from: _build/prod/lib/certifi
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > ssl_verify_fun-1.1.1
  |
  |  from: _build/prod/lib/ssl_verify_fun
  |  applications:
  |      :kernel
  |      :stdlib
  |      :ssl
  |  includes: none
  |_____

  > metrics-1.0.1
  |
  |  from: _build/prod/lib/metrics
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > hackney-1.13.0
  |
  |  from: _build/prod/lib/hackney
  |  applications:
  |      :kernel
  |      :stdlib
  |      :crypto
  |      :asn1
  |      :public_key
  |      :ssl
  |      :idna
  |      :mimerl
  |      :certifi
  |      :ssl_verify_fun
  |      :metrics
  |  includes: none
  |_____

  > tzdata-0.5.17
  |
  |  from: _build/prod/lib/tzdata
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :hackney
  |      :logger
  |  includes: none
  |_____

  > combine-0.10.0
  |
  |  from: _build/prod/lib/combine
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > timex-3.2.2
  |
  |  from: _build/prod/lib/timex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :tzdata
  |      :gettext
  |      :combine
  |  includes: none
  |_____

  > httpoison-1.2.0
  |
  |  from: _build/prod/lib/httpoison
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :hackney
  |  includes: none
  |_____

  > poison-3.1.0
  |
  |  from: _build/prod/lib/poison
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > cloudex-1.1.3
  |
  |  from: _build/prod/lib/cloudex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :poison
  |      :tzdata
  |      :timex
  |      :httpoison
  |  includes: none
  |_____

  > phoenix_pubsub-1.0.2
  |
  |  from: _build/prod/lib/phoenix_pubsub
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :crypto
  |  includes: none
  |_____

  > ranch-1.3.2
  |
  |  from: _build/prod/lib/ranch
  |  applications:
  |      :kernel
  |      :stdlib
  |      :ssl
  |  includes: none
  |_____

  > cowlib-1.0.2
  |
  |  from: _build/prod/lib/cowlib
  |  applications:
  |      :kernel
  |      :stdlib
  |      :crypto
  |  includes: none
  |_____

  > cowboy-1.1.2
  |
  |  from: _build/prod/lib/cowboy
  |  applications:
  |      :kernel
  |      :stdlib
  |      :ranch
  |      :cowlib
  |      :crypto
  |  includes: none
  |_____

  > xmerl-1.3.17
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/xmerl-1.3.17
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > syntax_tools-2.1.5
  |
  |  from: /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/lib/syntax_tools-2.1.5
  |  applications:
  |      :stdlib
  |  includes: none
  |_____

  > recon-2.3.2
  |
  |  from: _build/prod/lib/recon
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > rabbit_common-3.6.16
  |
  |  from: _build/prod/lib/rabbit_common
  |  applications:
  |      :kernel
  |      :stdlib
  |      :compiler
  |      :syntax_tools
  |      :xmerl
  |      :recon
  |  includes: none
  |_____

  > amqp_client-3.6.16
  |
  |  from: _build/prod/lib/amqp_client
  |  applications:
  |      :kernel
  |      :stdlib
  |      :xmerl
  |      :rabbit_common
  |  includes: none
  |_____

  > amqp-0.3.1
  |
  |  from: _build/prod/lib/amqp
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :amqp_client
  |  includes: none
  |_____

  > ulid-1.0.0
  |
  |  from: _build/prod/lib/ulid
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > mime-1.3.0
  |
  |  from: _build/prod/lib/mime
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > plug-1.6.1
  |
  |  from: _build/prod/lib/plug
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :crypto
  |      :logger
  |      :mime
  |  includes: none
  |_____

  > absinthe_plug-1.4.5
  |
  |  from: _build/prod/lib/absinthe_plug
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :plug
  |      :absinthe
  |  includes: none
  |_____

  > bodyguard-2.2.2
  |
  |  from: _build/prod/lib/bodyguard
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :plug
  |  includes: none
  |_____

  > cors_plug-1.5.2
  |
  |  from: _build/prod/lib/cors_plug
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > plug_attack-0.4.0
  |
  |  from: _build/prod/lib/plug_attack
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > inet_cidr-1.0.3
  |
  |  from: _build/prod/lib/inet_cidr
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > remote_ip-0.1.4
  |
  |  from: _build/prod/lib/remote_ip
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :plug
  |  includes:
  |      :combine
  |  :inet_cidr  |_____

  > eex-1.7.2
  |
  |  from: /Users/erikreedstrom/.asdf/installs/elixir/1.7.2/bin/../lib/eex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > phoenix-1.3.3
  |
  |  from: _build/prod/lib/phoenix
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :plug
  |      :poison
  |      :logger
  |      :eex
  |      :phoenix_pubsub
  |      :crypto
  |  includes: none
  |_____

  > base64url-0.0.1
  |
  |  from: _build/prod/lib/base64url
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > jose-1.8.4
  |
  |  from: _build/prod/lib/jose
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :crypto
  |      :asn1
  |      :public_key
  |      :base64url
  |  includes: none
  |_____

  > guardian-1.1.0
  |
  |  from: _build/prod/lib/guardian
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :crypto
  |      :logger
  |      :jose
  |      :poison
  |  includes: none
  |_____

  > sentry-6.4.1
  |
  |  from: _build/prod/lib/sentry
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :hackney
  |      :poison
  |      :logger
  |  includes: none
  |_____

  > abnf2-0.1.4
  |
  |  from: _build/prod/lib/abnf2
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > ex_cldr-1.6.4
  |
  |  from: _build/prod/lib/ex_cldr
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :abnf2
  |      :decimal
  |  includes: none
  |_____

  > ex_cldr_currencies-1.0.0
  |
  |  from: _build/prod/lib/ex_cldr_currencies
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :ex_cldr
  |  includes: none
  |_____

  > ex_cldr_numbers-1.5.1
  |
  |  from: _build/prod/lib/ex_cldr_numbers
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :decimal
  |      :ex_cldr
  |      :ex_cldr_currencies
  |  includes: none
  |_____

  > ex_cldr_lists-1.1.0
  |
  |  from: _build/prod/lib/ex_cldr_lists
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :jason
  |      :ex_cldr
  |      :ex_cldr_numbers
  |  includes: none
  |_____

  > connection-1.0.4
  |
  |  from: _build/prod/lib/connection
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > db_connection-1.1.3
  |
  |  from: _build/prod/lib/db_connection
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :connection
  |  includes: none
  |_____

  > postgrex-0.13.5
  |
  |  from: _build/prod/lib/postgrex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :db_connection
  |      :decimal
  |      :crypto
  |  includes: none
  |_____

  > poolboy-1.5.1
  |
  |  from: _build/prod/lib/poolboy
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > ecto-2.2.10
  |
  |  from: _build/prod/lib/ecto
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :decimal
  |      :poolboy
  |      :crypto
  |  includes: none
  |_____

  > absinthe_ecto-0.1.3
  |
  |  from: _build/prod/lib/absinthe_ecto
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :absinthe
  |      :ecto
  |  includes: none
  |_____

  > absinthe_relay-1.4.3
  |
  |  from: _build/prod/lib/absinthe_relay
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :absinthe
  |  includes: none
  |_____

  > decoratex-1.1.0
  |
  |  from: _build/prod/lib/decoratex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > msgpax-2.1.1
  |
  |  from: _build/prod/lib/msgpax
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > timber-2.8.2
  |
  |  from: _build/prod/lib/timber
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :poison
  |      :msgpax
  |      :hackney
  |  includes: none
  |_____

  > crontab-1.1.3
  |
  |  from: _build/prod/lib/crontab
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > quantum-2.2.7
  |
  |  from: _build/prod/lib/quantum
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :gen_stage
  |      :crontab
  |  includes: none
  |_____

  > ecto_enum-1.1.0
  |
  |  from: _build/prod/lib/ecto_enum
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :ecto
  |  includes: none
  |_____

  > task_bunny-0.3.3
  |
  |  from: _build/prod/lib/task_bunny
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :poison
  |      :amqp
  |  includes: none
  |_____

  > task_bunny_sentry-0.1.3
  |
  |  from: _build/prod/lib/task_bunny_sentry
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :sentry
  |      :task_bunny
  |  includes: none
  |_____

  > fast_yaml-1.0.11
  |
  |  from: _build/prod/lib/fast_yaml
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > approximate_histogram-0.1.1
  |
  |  from: _build/prod/lib/approximate_histogram
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > scout_apm-0.4.6
  |
  |  from: _build/prod/lib/scout_apm
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :hackney
  |      :plug
  |      :poison
  |      :approximate_histogram
  |  includes: none
  |_____

  > boltun-1.0.2
  |
  |  from: _build/prod/lib/boltun
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :postgrex
  |      :logger
  |  includes: none
  |_____

  > geo-3.0.0
  |
  |  from: _build/prod/lib/geo
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > geo_postgis-2.0.0
  |
  |  from: _build/prod/lib/geo_postgis
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :postgrex
  |      :geo
  |  includes: none
  |_____

  > phoenix_ecto-3.3.0
  |
  |  from: _build/prod/lib/phoenix_ecto
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :ecto
  |      :plug
  |  includes: none
  |_____

  > core_api-0.0.0+version
  |
  |  from: _build/prod/lib/core_api
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :runtime_tools
  |      :p1_utils
  |      :libcluster
  |      :swarm
  |      :elixir_uuid
  |      :format
  |      :elixlsx
  |      :inflex
  |      :gettext
  |      :sage
  |      :decimal
  |      :absinthe
  |      :jason
  |      :bcrypt_elixir
  |      :comeonin
  |      :flow
  |      :timex
  |      :httpoison
  |      :cloudex
  |      :phoenix_pubsub
  |      :cowboy
  |      :amqp
  |      :ulid
  |      :absinthe_plug
  |      :bodyguard
  |      :cors_plug
  |      :plug_attack
  |      :remote_ip
  |      :phoenix
  |      :guardian
  |      :sentry
  |      :ex_cldr_lists
  |      :postgrex
  |      :ecto
  |      :absinthe_ecto
  |      :absinthe_relay
  |      :decoratex
  |      :timber
  |      :quantum
  |      :ecto_enum
  |      :task_bunny
  |      :task_bunny_sentry
  |      :fast_yaml
  |      :scout_apm
  |      :boltun
  |      :geo_postgis
  |      :phoenix_ecto
  |  includes: none
  |_____

==> Running validation checks..
    > Mix.Releases.Checks.Erts * PASS
    > Mix.Releases.Checks.Cookie * PASS
    > Mix.Releases.Checks.MissingApps * WARN

One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

        :ex_machina
        :parse_trans

    This can cause your application to fail at runtime. If you are sure
    that this is not an issue, you may ignore this warning.

==> Generated overlay vars:
    release_name=:core_api
    release_version="0.0.0+version"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts=true
    include_src=false
    include_system_libs=true
    erl_opts=""
    run_erl_env=""
    erts_vsn="10.0.4"
    output_dir="_build/prod/rel/core_api"
==> Copying applications to _build/prod/rel/core_api
==> Generating start_erl.data
==> Generating vm.args from rel/vm.args
==> Generating sys.config from config/config.exs
==> Including ERTS 10.0.4 from /Users/erikreedstrom/.asdf/installs/erlang/21.0.4/erts-10.0.4
==> Generating boot script
==> Generating RELEASES
==> Generating start_clean.boot
==> Generating no_dot_erlang.boot
==> Applying overlays
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/pre_configure.d
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/post_configure.d
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/pre_start.d
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/post_start.d
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/pre_stop.d
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/post_stop.d
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/pre_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.0.0+version/hooks/post_upgrade.d
==> Applying copy overlay
    src: rel/hooks/pre_start
    dst: releases/0.0.0+version/hooks/pre_start.d
==> Applying copy overlay
    src: _build/prod/lib/distillery/priv/libexec
    dst: releases/0.0.0+version/libexec
==> Applying mkdir overlay
    dst: releases/0.0.0+version/commands
==> Packaging release..
==> Archiving core_api-0.0.0+version
==> Writing archive to /Users/erikreedstrom/Projects/homepolish/core_api/_build/prod/rel/core_api/releases/0.0.0+version/core_api.tar.gz
==> Updating archive..
==> Including system libs from current Erlang installation
==> Saving archive..
==> Archive saved!
Release succesfully built!
To start the release you have built, you can use one of the following tasks:

    # start a shell, like 'iex -S mix'
    > _build/prod/rel/core_api/bin/core_api console

    # start in the foreground, like 'mix run --no-halt'
    > _build/prod/rel/core_api/bin/core_api foreground

    # start in the background, must be stopped with the 'stop' command
    > _build/prod/rel/core_api/bin/core_api start

If you started a release elsewhere, and wish to connect to it:

    # connects a local shell to the running node
    > _build/prod/rel/core_api/bin/core_api remote_console

    # connects directly to the running node's console
    > _build/prod/rel/core_api/bin/core_api attach

For a complete listing of commands and their use:

    > _build/prod/rel/core_api/bin/core_api help
```

  </details>
</summary>

### Description of issue

- What are the expected results?

Application starts without issue.

- What version of Distillery?

2.0-rc8

- What OS, Erlang/Elixir versions are you seeing this issue on?

OS X 10.13.6, 21.0.4/1.7.2

- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)

<summary>
  <details>

```
# Import all plugins from `rel/plugins`
# They can then be used by adding `plugin MyPlugin` to
# either an environment, or release definition, where
# `MyPlugin` is the name of the plugin module.
Path.join(["rel", "plugins", "*.exs"])
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
  # This sets the default release built by `mix release`
  default_release: :default,
  # This sets the default environment used by `mix release`
  default_environment: Mix.env()

# For a full list of config options for both releases
# and environments, visit https://hexdocs.pm/distillery/configuration.html

# You may define one or more environments in this file,
# an environment's settings will override those of a release
# when building in that environment, this combination of release
# and environment configuration is called a profile

environment :dev do
  # If you are running Phoenix, you should make sure that
  # server: true is set and the code reloader is disabled,
  # even in dev mode.
  # It is recommended that you build with MIX_ENV=prod and pass
  # the --env flag to Distillery explicitly if you want to use
  # dev mode.
  set(dev_mode: true)
  set(include_erts: false)
  set(cookie: :"IJeobJ3Y>|3Q~P|L~$F&YuV)`f!8$EaZOnpN[Z(UOstDk/qEz6BSBAnKo&E&l(!3")
end

environment :prod do
  set(include_erts: true)
  set(include_src: false)
  # this is just to get rid of the warning. see https://github.com/bitwalker/distillery/issues/140
  set(cookie: :"${MY_COOKIE}")
  set(vm_args: "rel/vm.args")
  set(pre_start_hooks: "rel/hooks/pre_start")
end

# You may define one or more releases in this file.
# If you have not set a default release, or selected one
# when running `mix release`, the first release in the file
# will be used by default

release :core_api do
  set(version: current_version(:core_api))

  set(
    applications: [
      :runtime_tools
    ]
  )
end
```

  </details>
</summary>

**Comment by erikreedstrom** [comment]
This may have been a result of a change in how we use config.exs. I've now added the config to the overlays, but cannot verify as the config is now bailing with

```
no function clause matching in Keyword.merge/3
    (elixir) lib/keyword.ex:760: Keyword.merge(%{"application/octet-stream" => ["xlsx"], "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" => ["xlsx"]}, %{"application/octet-stream" => ["xlsx"], "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" => ["xlsx"]}, #Function<7.24821186/3 in Mix.Config.merge/2>)
    (elixir) lib/keyword.ex:773: Keyword.do_merge/6
    (distillery) lib/mix/lib/releases/config/providers/elixir.ex:66: anonymous fn/1 in Mix.Releases.Config.Providers.Elixir.merge_config/1
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (distillery) lib/mix/lib/releases/config/providers/elixir.ex:46: Mix.Releases.Config.Providers.Elixir.init/1
    (distillery) lib/mix/lib/releases/config/provider.ex:97: anonymous fn/2 in Mix.Releases.Config.Provider.init/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (distillery) lib/mix/lib/releases/config/provider.ex:88: Mix.Releases.Config.Provider.init/1
```

Seems like it's trying to merge the map provided for custom mime types as a Keyword list.

**Comment by bitwalker** [comment]
I've pushed a number of changes in rc.10, can you let me know if you are still seeing the issue, or any new ones for that matter?

**Comment by erikreedstrom** [comment]
We cleaned and rebuilt from scratch, but issue still exists.

**Comment by bitwalker** [comment]
I'm not sure how to reproduce this, do you have a repo I can clone or steps to reproduce? I don't see this my two test applications

**Comment by erikreedstrom** [comment]
This may have been an issue related to configuration. Now that #477 has been resolved, this issue is no longer present.

Thanks for all the help @bitwalker !!!
