### ISSUE TITLE
Ubuntu 16.04 Phoenix app failing to start

### ISSUE THREAD

**Issue by VladShcherbin** [bitwalker/distillery#54]
Okay, I kinda tried to google and try different combos, but still no luck.

Ubuntu 16.04, erlang & elixir are installed there. So, I guess, I can use `set include_erts: false`.

Versions:

- Erlang/OTP 19 [erts-8.0] [source] [64-bit]
- Elixir 1.3.2

The app is using the latest Phoenix and works if I manually start it, but the release want's something from me.

I'm kinda new with releases, here is the console output:

```sh
{"init terminating in do_boot",{load_failed,[error_handler]}}
```

I can do provide any info needed, just want to make it work finally :)

**Comment by bitwalker** [comment]
If you can paste your `mix.exs`, `rel/config.exs`, and the output of the release command with `--verbose`, I can get you sorted :)

**Comment by VladShcherbin** [comment]
Sure,

mix.exs

```exs
defmodule GreenWorks.Mixfile do
  use Mix.Project

  def project do
    [app: :greenworks,
     version: "0.0.1",
     elixir: "~> 1.2",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix, :gettext] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     aliases: aliases(),
     deps: deps()]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [mod: {GreenWorks, []},
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [{:phoenix, "~> 1.2.1"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"},
     {:distillery, "~> 0.9"}]
  end

  # Aliases are shortcuts or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
     "ecto.reset": ["ecto.drop", "ecto.setup"],
     "test": ["ecto.create --quiet", "ecto.migrate", "test"]]
  end
end

```

config.exs

```exs
use Mix.Releases.Config,
    # This sets the default release built by `mix release`
    default_release: :default,
    # This sets the default environment used by `mix release`
    default_environment: :dev

# For a full list of config options for both releases
# and environments, visit https://hexdocs.pm/distillery/configuration.html


# You may define one or more environments in this file,
# an environment's settings will override those of a release
# when building in that environment, this combination of release
# and environment configuration is called a profile

environment :dev do
  set dev_mode: true
  set include_erts: false
end

environment :prod do
  set include_erts: false
  set include_src: false
end

# You may define one or more releases in this file.
# If you have not set a default release, or selected one
# when running `mix release`, the first release in the file
# will be used by default

release :greenworks do
  set version: current_version(:greenworks)
end
```

MIX_ENV=prod mix release --env=prod --verbose

```exs
==> Loading configuration..
==> Assembling release..
==> Building release greenworks:0.0.1 using environment prod
==> One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:



    This can cause your application to fail at runtime. If you are sure
    that this is not an issue, you may ignore this warning.

==> Discovered applications:
  sasl-2.7
    from: /usr/local/Cellar/erlang/18.3/lib/erlang/lib/sasl-2.7
    applications:
      :kernel
      :stdlib
    includes: none

  iex-1.3.0
    from: /usr/local/Cellar/elixir/1.3.0/bin/../lib/iex
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  greenworks-0.0.1
    from: _build/prod/lib/greenworks
    applications:
      :kernel
      :stdlib
      :elixir
      :phoenix
      :phoenix_pubsub
      :phoenix_html
      :cowboy
      :logger
      :gettext
      :phoenix_ecto
      :postgrex
    includes: none

  kernel-4.2
    from: /usr/local/Cellar/erlang/18.3/lib/erlang/lib/kernel-4.2
    applications: none
    includes: none

  stdlib-2.8
    from: /usr/local/Cellar/erlang/18.3/lib/erlang/lib/stdlib-2.8
    applications:
      :kernel
    includes: none

  elixir-1.3.0
    from: /usr/local/Cellar/elixir/1.3.0/bin/../lib/elixir
    applications:
      :kernel
      :stdlib
      :compiler
    includes: none

  compiler-6.0.3
    from: /usr/local/Cellar/erlang/18.3/lib/erlang/lib/compiler-6.0.3
    applications:
      :kernel
      :stdlib
    includes: none

  phoenix-1.2.1
    from: _build/prod/lib/phoenix
    applications:
      :kernel
      :stdlib
      :elixir
      :plug
      :poison
      :logger
      :eex
    includes: none

  plug-1.2.0
    from: _build/prod/lib/plug
    applications:
      :kernel
      :stdlib
      :elixir
      :crypto
      :logger
      :mime
    includes: none

  crypto-3.6.3
    from: /usr/local/Cellar/erlang/18.3/lib/erlang/lib/crypto-3.6.3
    applications:
      :kernel
      :stdlib
    includes: none

  logger-1.3.0
    from: /usr/local/Cellar/elixir/1.3.0/bin/../lib/logger
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  mime-1.0.1
    from: _build/prod/lib/mime
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  poison-2.2.0
    from: _build/prod/lib/poison
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  eex-1.3.0
    from: /usr/local/Cellar/elixir/1.3.0/bin/../lib/eex
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  phoenix_pubsub-1.0.0
    from: _build/prod/lib/phoenix_pubsub
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :crypto
    includes: none

  phoenix_html-2.6.2
    from: _build/prod/lib/phoenix_html
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :plug
    includes: none

  cowboy-1.0.4
    from: _build/prod/lib/cowboy
    applications:
      :kernel
      :stdlib
      :ranch
      :cowlib
      :crypto
    includes: none

  ranch-1.2.1
    from: _build/prod/lib/ranch
    applications:
      :kernel
      :stdlib
    includes: none

  cowlib-1.0.2
    from: _build/prod/lib/cowlib
    applications:
      :kernel
      :stdlib
      :crypto
    includes: none

  gettext-0.11.0
    from: _build/prod/lib/gettext
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
    includes: none

  phoenix_ecto-3.0.1
    from: _build/prod/lib/phoenix_ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :ecto
      :plug
    includes: none

  ecto-2.0.4
    from: _build/prod/lib/ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :decimal
      :poolboy
    includes: none

  decimal-1.1.2
    from: _build/prod/lib/decimal
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  poolboy-1.5.1
    from: _build/prod/lib/poolboy
    applications:
      :kernel
      :stdlib
    includes: none

  postgrex-0.11.2
    from: _build/prod/lib/postgrex
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :db_connection
      :decimal
    includes: none

  db_connection-1.0.0-rc.5
    from: _build/prod/lib/db_connection
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :connection
    includes: none

  connection-1.0.4
    from: _build/prod/lib/connection
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

==> Generated overlay vars:
    release_name=:greenworks
    release_version="0.0.1"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts=false
    include_src=false
    include_system_libs=true
    erl_opts=""
    erts_vsn=nil
    output_dir="rel/greenworks"
==> Copying applications to rel/greenworks
==> Generating nodetool
==> Generating start_erl.data
==> Generating vm.args
==> Generating sys.config from config/config.exs
==> Generating boot script
==> Generating RELEASES
==> Generating start_clean.boot
==> Applying overlays
==> Applying mkdir overlay
    dst: releases/0.0.1/hooks
==> Applying mkdir overlay
    dst: releases/0.0.1/commands
==> Packaging release..
==> Archiving greenworks-0.0.1
==> Writing tarball to rel/greenworks/releases/0.0.1/greenworks.tar.gz
==> Updating tarball
==> Tarball updated!
==> Release successfully built!
```

**Comment by bitwalker** [comment]
Could you try master real quick? There are fixes I haven't released yet and I suspect they may help here. Could you also gist the `erl_crash.dump` file if that doesn't work? I can use that to figure out why the VM is crashing.

**Comment by VladShcherbin** [comment]
@bitwalker When using `{:distillery, github: "bitwalker/distillery"}]` and `MIX_ENV=prod mix release --env=prod`, it gives me the error:

```sh
** (FunctionClauseError) no function clause matching in Mix.Releases.Assembler.get_erts_version/1

lib/mix/lib/releases/assembler.ex:710: Mix.Releases.Assembler.generate_overlay_vars/1
lib/mix/lib/releases/assembler.ex:30: Mix.Releases.Assembler.assemble/1
lib/distillery/tasks/release.ex:106: Mix.Tasks.Release.run/1
(mix) lib/mix/task.ex:296: Mix.Task.run_task/3
(mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
...

Mac os, Erlang/OTP 18 [erts-7.3] [source] [64-bit], Elixir 1.3.0.

Reverting to 9.6 works. Maybe I'm missing something?

**Comment by bitwalker** [comment]
Oh man, I didn't add a clause for `include_erts` being false /facepalm

I'm not at my computer right now, but if you want to get adventurous you can edit `assembler.ex` and move the clause for true below the one for a path, and change it to be a catch all (the behavior should be the same for both true and false). I'll log on in a bit and push the fix

**Comment by VladShcherbin** [comment]
I tried, but unfortunately didn't figure it out. I'll be here when you'll push the fix so we'll continue our journey :)

**Comment by bitwalker** [comment]
Just pushed 0.9.7, want to give it a shot?

**Comment by VladShcherbin** [comment]
Oh nice, now it successfully started and ping is working. Still not showing the webpage, but I think we are very close.

```exs
root: ".",
server: true,
version: Mix.Project.config[:version]
```

Do I need to set this in the prod.config with the distillery? And where to run the `phoenix.digest`, locally or with some hook after deployed?

**Comment by bitwalker** [comment]
Yeah you'll need that in `config/prod.config`, and you'll want to run `mix phoenix.digest` prior to running `MIX_ENV=prod mix release --env=prod`. I generally glue the commands together during builds like so: `MIX_ENV=prod mix do compile, phoenix.digest, release --env=prod --verbose` (I always run with `--verbose` since if anything goes wrong I don't have to run it again, but it's by no means necessary).

**Comment by VladShcherbin** [comment]
Awesome, everything is working now! I really missed such a warm greeting and desire to help from a package creator.

Thank you a lot, I appreciate this. You are my hero! 🎉 👍

**Comment by bitwalker** [comment]
Hey that's great! Let me know if you run into any other issues. And thanks for the kind words, means a lot:)

**Comment by VladShcherbin** [comment]
@bitwalker I've got a small new question:

I have a file `priv/dir/file.js`, not in the static folder (as I don't want it to be public). In my controller I need to specify its path:

```elixir
result = App.ReactIO.json_call!(%{
  component: "priv/dir/file.js"
})
```

It works fine locally, but on the server it keeps telling me:

```sh
Cannot load component: priv/dir/file.js
```

How can this be fixed?

**Comment by VladShcherbin** [comment]
Not sure if this is the correct way, solved by:

```exs
Path.join("#{:code.priv_dir(:myapp)}", "dir/file.js"),
```

**Comment by bitwalker** [comment]
@VladShcherbin Yep that's the correct solution. I can add a note about that in the docs, great suggestion!

**Comment by VladShcherbin** [comment]
@bitwalker would be great, thanks.

The last issue (or a bug) I have it that `start` command is not working on the server (locally everything is working fine on OS X).

If I remember correct, same was with even the first release. So, basically:
- `start` does nothing
- `forceground` starts the server, `ctrc + c` exits, but the server is still running and even sending logs in the shell
- `stop` successfully stops previous `forceground`

Maybe we can somehow test it too?

**Comment by bitwalker** [comment]
After running `start` are you running `ping` to verify whether it's up or not? `start` doesn't display anything in the shell. If ctrl+c is not exiting the foreground process, it means some application is hanging when being asked to shutdown more than likely, that said, do you have a repo I can reproduce with? That will help me figure out what's going wrong here.

**Comment by VladShcherbin** [comment]
@bitwalker yes, I tried `ping`, but no pong received. The app is kinda big & not open source, I'll try to make a small reproduce repo a bit later.

**Comment by VladShcherbin** [comment]
@bitwalker okay, here is simple [repo](https://github.com/VladShcherbin/distillery-test) for the test with all the commands needed.

Tested on fresh ubuntu 16.04 vps. Same result with installing erlang / elixir.

**Comment by bitwalker** [comment]
@VladShcherbin thanks for putting that together, I'll test in the morning and figure out what's going on

**Comment by VladShcherbin** [comment]
@bitwalker Hey, I think this is the same issue as this [https://github.com/bitwalker/distillery/issues/59]. Lets move there I guess :)
