### ISSUE TITLE
[OpenBSD] Cannot stop app

### ISSUE THREAD

**Issue by siegfried** [bitwalker/distillery#634]
### Steps to reproduce

Stop any running release created by Distillery on OpenBSD 6.4.

### Verbose Logs

Paste the output of the release command you ran with the `--verbose` flag
below in the summary tags (this helps keep the issue easy to navigate):

<summary>
  <details>

```
# bin/myproject stop --verbose
tput: not enough arguments (3) for capability `setaf'
tput: not enough arguments (3) for capability `setaf'
tput: not enough arguments (3) for capability `setaf'
tput: not enough arguments (3) for capability `setaf'
warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
** (exit) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib) gen.erl:261: :gen.do_for_proc/2
    (stdlib) gen_event.erl:197: :gen_event.rpc/2
    (artificery) lib/console.ex:281: Artificery.Console.init/0
    (distillery) lib/entry.ex:42: Mix.Releases.Runtime.Control.main/1
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/code.ex:232: Code.eval_string/3
Node myproject@127.0.0.1 is not running!
```

  </details>
</summary>

### Description of issue

- What are the expected results?
The application should be stopped, but it is still running.

- What version of Distillery?
I use the master branch. 
`{:git, "https://github.com/bitwalker/distillery.git", "b945641ebbc17848378f4cd0f1c116ec78326ad4", []}`

- What OS, Erlang/Elixir versions are you seeing this issue on?
OS: OpenBSD 6.4
Erlang/OTP 19
Elixir 1.7.3

- If possible, also provide your `rel/config.exs`, as it is often
```
# Import all plugins from `rel/plugins`
# They can then be used by adding `plugin MyPlugin` to
# either an environment, or release definition, where
# `MyPlugin` is the name of the plugin module.
~w(rel plugins *.exs)
|> Path.join()
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    # This sets the default release built by `mix release`
    default_release: :default,
    # This sets the default environment used by `mix release`
    default_environment: Mix.env()

# For a full list of config options for both releases
# and environments, visit https://hexdocs.pm/distillery/config/distillery.html


# You may define one or more environments in this file,
# an environment's settings will override those of a release
# when building in that environment, this combination of release
# and environment configuration is called a profile

environment :dev do
  # If you are running Phoenix, you should make sure that
  # server: true is set and the code reloader is disabled,
  # even in dev mode.
  # It is recommended that you build with MIX_ENV=prod and pass
  # the --env flag to Distillery explicitly if you want to use
  # dev mode.
  set dev_mode: true
  set include_erts: false
  set cookie: :"=*L{o~h2[svM1lBDk8,ihN!d[U>,u;>L=V,Ee:2VC3Ja8pS(c9nNK,vHaHIJLP^W"
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"s`UDf0Y$W=~`&SGS~abw_a;2cs/?rR@fd^Jth@)2d5%JNiIJjiG2[|lL~}A6rJv_"
  set vm_args: "rel/vm.args"
  set config_providers: [
    {Toml.Provider, [path: "${RELEASE_ROOT_DIR}/config.toml"]}
  ]
  set overlays: [
    {:copy, "config/defaults.toml", "config.toml"}
  ]
end

# You may define one or more releases in this file.
# If you have not set a default release, or selected one
# when running `mix release`, the first release in the file
# will be used by default

release :myproject do
  set version: current_version(:myproject)
  set applications: [
    :runtime_tools
  ]
end
```

- Is there documentation that says one thing, but Distillery does
  another? If so, please link the doc here so it can be updated if
  it's a documentation issue, or so that the fix can be based around
  what's documented.
According to the Distillery issues I had in the past on OpenBSD, I guess it is related to some misuse of shell commands. I can help to debug it if you can tell me where to start. Thanks.

- If this is a runtime configuration issue, please also provide your config file 
  (with any sensitive information stripped of course). This is almost
  always necessary to understand why some configuration may not be working.

**Comment by siegfried** [comment]
This also prevent app from being upgraded.

**Comment by siegfried** [comment]
I guess this issue is related to #561.

**Comment by siegfried** [comment]
Cannot reproduce it anymore after I upgrade OpenBSD (to 6.5) along with Erlang/Elixir.
